from app.repositories.user_repository import UserRepository
from app.repositories.task_repository import TaskRepository
from app.repositories.category_repository import CategoryRepository
from app.repositories.activity_repository import ActivityRepository
from app.repositories.life_goal_repository import LifeGoalRepository
